# SMS SPAM CLASSIFIER PROJECT

In [1]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("./dataset/spam.csv", encoding="latin-1")

In [9]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
3029,ham,"Also sir, i sent you an email about how to log...",NaN,NaN,NaN
1886,spam,Dear 0776xxxxxxx U've been invited to XCHAT. T...,NaN,NaN,NaN
3320,ham,Yo im right by yo work,NaN,NaN,NaN
1377,spam,Double Mins & Double Txt & 1/2 price Linerenta...,NaN,NaN,NaN
2345,ham,"Hi this is yijue, can i meet u at 11 tmr?",NaN,NaN,NaN

In [10]:
df.shape

(5572, 5)

## Steps:
1. Data Cleaning
2. EDA
3. Text Preprossesing
4. Model Building
5. Evaluation
6. Improvent
7. Website
8. Deployment

## 1. DATA CLEANING

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [12]:
# Drop last 3 columns - Pretty much useless
df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"], inplace=True)

In [13]:
df.sample(5)

        v1                                                 v2
5139   ham  Oh shut it. Omg yesterday I had a dream that I...
3596  spam  Congratulations YOU'VE Won. You're a Winner in...
5493   ham  I think if he rule tamilnadu..then its very to...
3718  spam  Thanks for your ringtone order, reference numb...
2143   ham  You stayin out of trouble stranger!!saw Dave t...

In [14]:
# Renaming columns v1,v2 as they are not descriptive
df.rename(columns={"v1" : "target", "v2":"text"}, inplace=True)

In [15]:
df.sample(5)

     target                                               text
2911    ham  You didn't have to tell me that...now i'm thin...
1910    ham  Becoz its  &lt;#&gt;  jan whn al the post ofic...
4687    ham           Hmmm.but you should give it on one day..
1327   spam  Ur balance is now å£500. Ur next question is: ...
4227    ham                           Have you started in skye

In [16]:
# We need integer target values so lets transform those
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [19]:
df["target"] = encoder.fit_transform(df["target"])

In [20]:
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# Missing values check
df.isnull().sum()

target    0
text      0
dtype: int64

In [24]:
# Check for duplicate values
df.duplicated().sum()

np.int64(403)

In [25]:
# Remove duplicate
df.drop_duplicates(keep='first', inplace=True)

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.shape

(5169, 2)